[package]
name = "anders-cli"
version = "0.1.0"
authors = ["Sebastian Thiel <byronimo@gmail.com>"]

[[bin]]
name = "anders"

[dependencies]
clap = "^ 2"
quick-error = "1"
anders = { path = "../lib" }

[profile.release]
lto = true
# Only on nightly, but reduces file-size by 230kb
# opt-level = "z"
